const dateToday = new Date();

const dateYesterday = new Date(
  dateToday.getFullYear(),
  dateToday.getMonth(),
  dateToday.getDate() - 1,
);

const dateTomorrow = new Date(
  dateToday.getFullYear(),
  dateToday.getMonth(),
  dateToday.getDate() + 1,
);

const dateNextYear = new Date(
  dateToday.getFullYear() + 1,
  dateToday.getMonth(),
  dateToday.getDate(),
);

const dateLastYear = new Date(
  dateToday.getFullYear() - 1,
  dateToday.getMonth(),
  dateToday.getDate(),
);

export default [
  {
    id: 1,
    name: "Book flights to Japan",
    description: "Compare ticket prices and finalize travel dates.",
    project: "Travel",
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: dateToday,
    doneDate: null,
  },
  {
    id: 2,
    name: "Finish quarterly report",
    description: "Compile all department updates and review with manager.",
    project: "Work",
    done: true,
    addedDate: new Date("2025-04-15"),
    dueDate: dateToday,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 3,
    name: "Clean out garage",
    description: "Sort tools, recycle old items, and organize storage.",
    project: "Home",
    done: true,
    addedDate: new Date("2025-04-14"),
    dueDate: dateToday,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 4,
    name: "Buy groceries",
    description: "Milk, eggs, bread, fruit, and coffee.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: dateToday,
    doneDate: null,
  },
  {
    id: 5,
    name: "Submit tax documents",
    description: "Upload to accountant’s portal.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-05"),
    dueDate: dateYesterday,
    doneDate: null,
  },
  {
    id: 6,
    name: "Pack suitcase",
    description: "Prepare for 2-week trip. Don’t forget chargers and passport.",
    project: "Travel",
    done: true,
    addedDate: new Date("2025-04-12"),
    dueDate: dateYesterday,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 7,
    name: "Mow the lawn",
    description: "Check mower gas before starting.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-16"),
    dueDate: dateYesterday,
    doneDate: null,
  },
  {
    id: 8,
    name: "Plan weekend hiking trip",
    description: "Pick a trail and invite friends.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-14"),
    dueDate: dateYesterday,
    doneDate: null,
  },
  {
    id: 9,
    name: "Update LinkedIn profile",
    description: "Add recent projects and certifications.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-17"),
    dueDate: dateTomorrow,
    doneDate: null,
  },
  {
    id: 10,
    name: "Schedule dentist appointment",
    description: "Check insurance and pick a date.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-18"),
    dueDate: dateTomorrow,
    doneDate: null,
  },
  {
    id: 11,
    name: "Research Airbnb options",
    description: "Filter by reviews and location.",
    project: "Travel",
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: dateNextYear,
    doneDate: null,
  },
  {
    id: 12,
    name: "Paint the guest room",
    description: "Pick a calming color and get supplies.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-03"),
    dueDate: dateLastYear,
    doneDate: null,
  },
  {
    id: 13,
    name: "Organize team meeting",
    description: "Set agenda and send invites.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: new Date("2025-04-22"),
    doneDate: null,
  },
  {
    id: 14,
    name: "Buy a gift for Sam",
    description: "Birthday is coming up soon!",
    project: null,
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: new Date("2025-05-03"),
    doneDate: null,
  },
  {
    id: 15,
    name: "Finish packing boxes",
    description: "Label them clearly before moving.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-08"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 16,
    name: "Create travel itinerary",
    description: "Include hotels, activities, and restaurants.",
    project: "Travel",
    done: false,
    addedDate: new Date("2025-04-14"),
    dueDate: new Date("2025-05-30"),
    doneDate: null,
  },
  {
    id: 17,
    name: "Set up standing desk",
    description: "Assemble parts and adjust height.",
    project: "Home",
    done: true,
    addedDate: new Date("2025-04-17"),
    dueDate: null,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 18,
    name: "Send feedback to designer",
    description: "Review draft and provide detailed notes.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-15"),
    dueDate: new Date("2025-04-21"),
    doneDate: null,
  },
  {
    id: 19,
    name: "Make a vision board",
    description: "Collect images and quotes for inspiration.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-01"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 20,
    name: "Cancel gym membership",
    description: "Switching to home workouts.",
    project: null,
    done: true,
    addedDate: new Date("2025-04-05"),
    dueDate: null,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 21,
    name: "Renew car insurance",
    description: "Compare offers and renew before expiration.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-12"),
    dueDate: new Date("2025-05-05"),
    doneDate: null,
  },
  {
    id: 22,
    name: "Write blog post",
    description: "Topic: Remote work productivity hacks.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-01"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 23,
    name: "Print boarding passes",
    description: "Double-check gate number and departure time.",
    project: "Travel",
    done: true,
    addedDate: new Date("2025-04-10"),
    dueDate: new Date("2025-04-17"),
    doneDate: new Date("2025-04-17"),
  },
  {
    id: 24,
    name: "Organize bookshelf",
    description: "Donate unread books to the library.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-03"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 25,
    name: "Call grandma",
    description: "Catch up and plan a visit.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: new Date("2025-04-21"),
    doneDate: null,
  },
  {
    id: 26,
    name: "Create slide deck for client",
    description: "Include updated metrics and branding.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: new Date("2025-04-26"),
    doneDate: null,
  },
  {
    id: 27,
    name: "Order travel-sized toiletries",
    description: "Sunscreen, shampoo, toothpaste, etc.",
    project: "Travel",
    done: true,
    addedDate: new Date("2025-04-07"),
    dueDate: null,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 28,
    name: "Install new door lock",
    description: "Smart lock with keypad entry.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-12"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 29,
    name: "Brainstorm Q2 goals",
    description: "Include team input and strategic priorities.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-15"),
    dueDate: new Date("2025-04-30"),
    doneDate: null,
  },
  {
    id: 30,
    name: "Pick up dry cleaning",
    description: "Before 6pm on Friday.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-15"),
    dueDate: new Date("2025-04-20"),
    doneDate: null,
  },
  {
    id: 31,
    name: "Plan meals for next week",
    description: "Include quick options for busy days.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 32,
    name: "Attend conference call",
    description: "Discussion about upcoming projects.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-20"),
    dueDate: new Date("2025-04-23"),
    doneDate: null,
  },
  {
    id: 33,
    name: "Get car oil change",
    description: "Schedule an appointment.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-19"),
    dueDate: new Date("2025-04-22"),
    doneDate: null,
  },
  {
    id: 34,
    name: "Clear out email inbox",
    description: "Unsubscribe from newsletters.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 35,
    name: "Prepare meeting notes",
    description: "Review last meeting’s action items.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: new Date("2025-04-22"),
    doneDate: null,
  },
  {
    id: 36,
    name: "Fix broken lightbulb",
    description: "Replace the bulb in the kitchen.",
    project: "Home",
    done: true,
    addedDate: new Date("2025-04-17"),
    dueDate: null,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 37,
    name: "Order new phone charger",
    description: "Ensure it's compatible with my phone model.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-15"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 38,
    name: "Read new book",
    description: "Currently reading 'The Subtle Art of Not Giving a F*ck'.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-14"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 39,
    name: "Create personal budget for next month",
    description: "Review last month's expenses and adjust.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-16"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 40,
    name: "Register for marathon",
    description: "Make sure to pick the right race category.",
    project: "Home",
    done: true,
    addedDate: new Date("2025-04-17"),
    dueDate: null,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 41,
    name: "Upgrade website portfolio",
    description: "Showcase recent projects and redesign sections.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-20"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 42,
    name: "Send invitations for dinner party",
    description: "Send out invites to 10 people.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-18"),
    dueDate: new Date("2025-04-30"),
    doneDate: null,
  },
  {
    id: 43,
    name: "Finish online course",
    description: "Complete the final project for certification.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-17"),
    dueDate: new Date("2025-05-10"),
    doneDate: null,
  },
  {
    id: 44,
    name: "Sign up for yoga class",
    description: "Check availability and schedule for classes.",
    project: "Home",
    done: true,
    addedDate: new Date("2025-04-17"),
    dueDate: null,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 45,
    name: "Install new app",
    description: "Try the new task management app.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 46,
    name: "Schedule annual health check-up",
    description: "Call the doctor's office and confirm dates.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-19"),
    dueDate: new Date("2025-05-15"),
    doneDate: null,
  },
  {
    id: 47,
    name: "Update resume",
    description: "Include recent work experience and skills.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-18"),
    dueDate: new Date("2025-04-25"),
    doneDate: null,
  },
  {
    id: 48,
    name: "Check in with project team",
    description: "Ensure tasks are on track for deadlines.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-15"),
    dueDate: new Date("2025-04-22"),
    doneDate: null,
  },
  {
    id: 49,
    name: "Take dog for a walk",
    description: "Walk the dog for 30 minutes in the evening.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-14"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 50,
    name: "Organize closet",
    description: "Sort through clothes and donate old items.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-01"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 51,
    name: "Check weather forecast for trip",
    description: "Plan accordingly based on weather predictions.",
    project: "Travel",
    done: false,
    addedDate: new Date("2025-04-15"),
    dueDate: new Date("2025-04-21"),
    doneDate: null,
  },
  {
    id: 52,
    name: "Clear out fridge",
    description: "Throw out expired items.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-12"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 53,
    name: "Send thank-you notes",
    description: "Express gratitude for recent gifts.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-14"),
    dueDate: new Date("2025-04-25"),
    doneDate: null,
  },
  {
    id: 54,
    name: "Write thank-you email to client",
    description: "Thank the client for their business and feedback.",
    project: "Work",
    done: true,
    addedDate: new Date("2025-04-17"),
    dueDate: null,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 55,
    name: "Arrange for pet sitter",
    description: "Find someone reliable to look after the dog.",
    project: null,
    done: false,
    addedDate: new Date("2025-04-19"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 56,
    name: "Fix kitchen sink",
    description: "Check if there are any leaks and repair.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-13"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 57,
    name: "Set up vacation auto-response",
    description: "Create an out-of-office email response.",
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-10"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 58,
    name: "Print photos for scrapbook",
    description: "Select and print the best moments.",
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-12"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 59,
    name: "Charge camera",
    description: "Ensure battery is full before trip.",
    project: "Travel",
    done: true,
    addedDate: new Date("2025-04-14"),
    dueDate: null,
    doneDate: new Date("2025-04-21"),
  },
  {
    id: 60,
    name: "Call insurance provider",
    description: null,
    project: null,
    done: true,
    addedDate: new Date("2025-04-13"),
    dueDate: new Date("2025-05-02"),
    doneDate: new Date("2025-04-20"),
  },
  {
    id: 61,
    name: "Design business cards",
    description: null,
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-12"),
    dueDate: new Date("2025-05-10"),
    doneDate: null,
  },
  {
    id: 62,
    name: "Confirm hotel reservation",
    description: null,
    project: "Travel",
    done: true,
    addedDate: new Date("2025-04-10"),
    dueDate: new Date("2025-06-05"),
    doneDate: new Date("2025-04-17"),
  },
  {
    id: 63,
    name: "Organize digital photos",
    description: null,
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-11"),
    dueDate: new Date("2025-05-12"),
    doneDate: null,
  },
  {
    id: 64,
    name: "Submit internship application",
    description: null,
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-11"),
    dueDate: new Date("2025-05-20"),
    doneDate: null,
  },
  {
    id: 65,
    name: "Schedule hair appointment",
    description: null,
    project: "Personal",
    done: true,
    addedDate: new Date("2025-04-12"),
    dueDate: new Date("2025-04-28"),
    doneDate: new Date("2025-04-18"),
  },
  {
    id: 66,
    name: "Install kitchen shelves",
    description: null,
    project: "Home",
    done: false,
    addedDate: new Date("2025-04-14"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 67,
    name: "Research travel insurance",
    description: null,
    project: "Travel",
    done: true,
    addedDate: new Date("2025-04-10"),
    dueDate: null,
    doneDate: new Date("2025-04-17"),
  },
  {
    id: 68,
    name: "Organize shared drive",
    description: null,
    project: "Work",
    done: false,
    addedDate: new Date("2025-04-12"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 69,
    name: "Set up budgeting spreadsheet",
    description: null,
    project: "Finance",
    done: false,
    addedDate: new Date("2025-04-11"),
    dueDate: null,
    doneDate: null,
  },
  {
    id: 70,
    name: "Buy paint samples",
    description: null,
    project: "Home",
    done: true,
    addedDate: new Date("2025-04-10"),
    dueDate: null,
    doneDate: new Date("2025-04-17"),
  },
];
